# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-10 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fans',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=30, verbose_name='用户感兴趣的方向')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'interests',
            },
        ),
        migrations.CreateModel(
            name='Interests_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('iid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Interests')),
            ],
            options={
                'db_table': 'interests_user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户昵称')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=11, verbose_name='联系电话')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('birthday', models.DateField()),
                ('isActive', models.BooleanField(default=False, verbose_name='是否激活')),
                ('profile_image_url', models.URLField(default='/static/default_pic/default_profile.jpg', verbose_name='头像')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='个性签名')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='WeiboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuid', models.CharField(db_index=True, max_length=50, verbose_name='微博用户id')),
                ('access_token', models.CharField(max_length=100, verbose_name='授权令牌')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('uid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'weibo_user',
            },
        ),
        migrations.AddField(
            model_name='interests_user',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='fans',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
