# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-13 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='ufollow',
        ),
        migrations.AlterModelTable(
            name='interests',
            table='uinterests',
        ),
        migrations.AlterModelTable(
            name='interests_user',
            table='uinterests_user',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='uuser_profile',
        ),
        migrations.AlterModelTable(
            name='weibouser',
            table='uweibo_user',
        ),
    ]
