# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-10 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fans',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='uid',
        ),
        migrations.AddField(
            model_name='follow',
            name='fans_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fans_id', to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followed_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followed_id', to='user.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Fans',
        ),
    ]
