# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-16 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191213_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.ImageField(default='/static/default_pic/default_profile.jpg', upload_to='', verbose_name='头像'),
        ),
    ]
