# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-18 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191216_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests_user',
            name='iid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Interests'),
        ),
        migrations.AlterField(
            model_name='interests_user',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
