# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-24 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191218_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowUser',
        ),
    ]
