# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191224_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuser',
            name='fans_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fans_id', to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='followed_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followed_id', to='user.UserProfile'),
        ),
    ]
