# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-20 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='collect_count',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='forward_count',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='like_count',
        ),
    ]
