# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-22 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20191220_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='blogpics', verbose_name='图片路径'),
        ),
    ]
