# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-23 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20191222_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='删除与否')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'ctag_blog',
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tid',
        ),
        migrations.AddField(
            model_name='tag_blog',
            name='blog_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Blog'),
        ),
        migrations.AddField(
            model_name='tag_blog',
            name='tag_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Tag'),
        ),
    ]
