# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-25 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191224_1418'),
        ('community', '0005_blog_unique_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Blog')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'clike',
            },
        ),
    ]
