# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-14 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='source',
        ),
    ]
