# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-14 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191213_1619'),
        ('product', '0002_remove_sku_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Sku')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'plike',
            },
        ),
    ]
