# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-16 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_likeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku_img',
            name='img_url',
            field=models.ImageField(upload_to='', verbose_name='sku图片'),
        ),
    ]
