# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-18 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20191216_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='sku_id',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
