# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-18 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191218_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(verbose_name='Logo图片'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='default_img_url',
            field=models.URLField(verbose_name='sku图片'),
        ),
        migrations.AlterField(
            model_name='sku_img',
            name='img_url',
            field=models.URLField(verbose_name='sku图片'),
        ),
    ]
