# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191218_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_url',
            field=models.ImageField(upload_to='', verbose_name='Logo图片'),
        ),
    ]
