# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-21 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191219_1929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='ReplyProduct',
        ),
        migrations.AlterField(
            model_name='spu',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='spu',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
