# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20191221_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spu',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spu',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
