# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20191221_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_attr_val',
            name='val',
            field=models.CharField(default='', max_length=50, verbose_name='产品属性值'),
        ),
    ]
