# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191218_2023'),
        ('product', '0012_auto_20191222_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Sku')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'pscore',
            },
        ),
    ]
