# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-27 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191224_1418'),
        ('product', '0013_productscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictSkuScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_score', models.FloatField(verbose_name='预测分数')),
                ('product_type', models.IntegerField(verbose_name='从产品分类')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Sku')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'predict_sku_score',
            },
        ),
    ]
